[workspace]
authors = ["Charles-Antoine Leger <ca@leger.email>"]
channels = ["conda-forge"]
name = "practical-4"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.11.*"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
eurybia = ">=1.3.3, <2"
alibi-detect = ">=0.12.0, <0.13"
keras = "==2.14.0"
tf-keras = ">=2.15.0, <3"
tensorflow = ">=2.14.1, <3"
tensorflow-probability = "==0.22.1"
